### ISSUE TITLE
Not working with 5 zig

### ISSUE THREAD

**Issue by chilletize** [KurodaAkira/RPG-Hud#60]
I added this mod to my pack, and it doesn't let my 5zig work for some reason. Any solutions?

**Comment by Raelzaryn** [comment]
Please provide more information.
Mc version?
Version of both mods.
What exactly isn't working (crash log?)
How can you reproduce the problem?

**Comment by chilletize** [comment]
Version 1.8.9
5 zig version 3.14 and HUD mod version latest
The Hud mod doesn't work (No crash log)
To reproduce it put the 2 mods in and try to play (Might be caused by Optifine too, not sure)

**Comment by Raelzaryn** [comment]
there was a major bug in 1.8.9 which prevented the HUD from rendering. This is fixed with the 3.8 version of the mod.

**Comment by chilletize** [comment]
This is still an issue with 5zig v3.14.1 and RPG-Hud 3.8.1, some styles don't let 5zig render. Eg. Modern but Extended works fine with 5zig.
